### PR TITLE
171 Fix errors in Git for GraphQL

### LINKED ISSUE #171: Fix errors in Git for GraphQL
# Directory
```
query {
  repository(id:"ada/repo0") {
    commit(revision:"master") {
      directory(path:"inexistant") {
        path
      }
    }
  }
}
```
returns
```
{
  "data": {
    "repository": {
      "commit": null
    }
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Commit.directory"
    }
  ]
}
```

-----
# File
```
query {
  repository(id:"ada/repo0") {
    commit(revision:"master") {
      file(path:"inexistant") {
        path
      }
    }
  }
}
```
fails with
```
NoMethodError (undefined method `name' for nil:NilClass):

app/models/git_file.rb:16:in `initialize'
app/graphql/types/git/commit_type.rb:97:in `new'
app/graphql/types/git/commit_type.rb:97:in `block (3 levels) in <top (required)>'
app/graphql/instrumenters/validation_error_instrumenter.rb:16:in `block (2 levels) in instrument'
app/controllers/graphql_controller.rb:10:in `execute'
```

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #171. It also upgrades gitlab_git and adds a few more fields.

### CODE REVIEW

File: app/graphql/mutations/repository/git/set_default_branch_mutation.rb [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+      # GraphQL mutation to create a new tag
+      class SetDefaultBranchResolver
+        def call(repository, arguments, context)
+          arguments = arguments.to_h
+          if repository.git.find_branch(arguments['name'])
+            repository.git.default_branch = arguments['name']
+            repository.git.find_branch(repository.git.default_branch)
+          else
+            message = %(The branch "#{arguments['name']}" does not exist.)
```
Comment (phyrog) [inline app/graphql/mutations/repository/git/set_default_branch_mutation.rb]: Why this form of string interpolation?

File: app/graphql/types/git/commit_type.rb [hunk 2]
```diff
@@ -94,9 +94,19 @@
...
-                  arguments['path'],
-                  load_all_data: arguments['loadAllData'])
+      git_file = GitFile.new(commit,
+                             arguments['path'],
+                             load_all_data: arguments['loadAllData'])
+      git_file if git_file.exist?
+    end)
+  end
+
+  field :lsFiles, !types[!types.String] do
```
Comment (phyrog) [inline app/graphql/types/git/commit_type.rb]: What do you think about returning a list of files here instead of just a list of paths? Would that be computationally expensive to do?

File: app/models/git_file.rb [hunk 3]
```diff
@@ -11,35 +11,55 @@ class GitFile
...
-    blob.binary ? 'base64' : 'plain'
+    blob&.binary ? 'base64' : 'plain'
   end
 
   def gitlab
     @gitlab ||= Gitlab::Git::Wrapper.new(@commit.repository.path)
   end
 
+  def exist?
+    unless @existance_checked
```
Comment (phyrog) [inline app/models/git_file.rb]: I think you might write this as

```ruby
@existance_checked ||= !!check_existance
```

Not sure if it's more readable though

File: app/models/git_file.rb [hunk 4]
```diff
@@ -11,35 +11,55 @@ class GitFile
...
+  # it, we can load the path as well.
+  def load_name_and_path_from_blob
+    check_existance
+    return unless blob
+    @name = blob.name
+    @path = blob.path
+  end
+
+  # Checks the existance by loading the blob
+  def check_existance
```
Comment (phyrog) [inline app/models/git_file.rb]: Shouldn't this set `@exiatance_checked`?

File: app/graphql/mutations/repository/git/set_default_branch_mutation.rb (hunk 1 above)
Comment (eugenk) [inline app/graphql/mutations/repository/git/set_default_branch_mutation.rb]: Because I want to use double quotes in the string and don't want to escape them.

Comment (phyrog) [inline app/graphql/mutations/repository/git/set_default_branch_mutation.rb]: Ah ok, now I get it

File: app/graphql/types/git/commit_type.rb (hunk 2 above)
Comment (eugenk) [inline app/graphql/types/git/commit_type.rb]: We could do it without blowing up the computation time if we only query for `name` and `path`. However, it would be a blob lookup (including loading up to 10 MB of the data into memory per blob) for every file of the repository (some ontology repositories have many files) as soon as we query for more than just path and name.

I vote for not doing this.

File: app/models/git_file.rb (hunk 3 above)
Comment (eugenk) [inline app/models/git_file.rb]: Simplified in fdc916bb

File: app/models/git_file.rb (hunk 4 above)
Comment (eugenk) [inline app/models/git_file.rb]: Simplified in fdc916bb

File: app/models/git_file.rb (hunk 3 above)
Comment (phyrog) [inline app/models/git_file.rb]: Ah wait that is not the same (if `check_existance` returns a falsy value)

**Comment by eugenk** [comment]
Rebased on master
